[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --workspace=backend --include=dev"]

[phases.build]
cmds = ["npm run build --workspace=backend"]

[start]
cmd = "node backend/dist/index.js"
